### ISSUE TITLE
Error: Not found. The requested item was not found.

### ISSUE THREAD

**Issue by ramyaramdasan** [ServiceNow/sncicd-publish-app#9]
All these while, we have been testing the pipeline in ServiceNow provided DPP instances. For first time today, we did a trial run of the pipeline on our organization's live instances. The pipeline threw error at the Publish step. Other Actions like **servicenow-ci-cd-apply-changes** and **servicenow-ci-cd-run-atf-test-suite** ran successfully prior to the publish step. 

The application that is being published has been in the system for a few weeks now. It was deployed manually to TEST instance from sourcecontrol and Published manually from Studio in TEST until we automated it using the pipeline. Manual publish worked without any issue. Not sure if it makes any difference, we were publishing from main branch until now, but the pipeline will be publishing from the dev branch instead. 

![Publish Error](https://user-images.githubusercontent.com/62088522/109259960-41ea6180-7823-11eb-9c70-f0e5a62e6736.png)

**Comment by chiarnglin** [comment]
Noting for the record that Ramya dug into the issue, and the reason was because the `sn_cicd.sys_ci_automation` role only allowed "Apply Remote Changes" and "Run ATF Test Suite", but did not allow "Publish to App Repo". 

https://docs.servicenow.com/bundle/paris-application-development/page/build/applications/task/t_PublishAppsToTheAppRepository.html

> "Role required: admin, or delegated_developer with Publish To App Repo permission enabled"

Therefore, try delegated dev with "publish to app repo" enabled.

**Comment by ramyaramdasan** [comment]
The proposed solution was tried and found working. Thanks @chiarnglin!
